// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamaCardAll.Infra;

#nullable disable

namespace SamaCardAll.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014194335_AddIntUserIdToCardAndCustomer")]
    partial class AddIntUserIdToCardAndCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SamaCardAll.Core.Models.Card", b =>
                {
                    b.Property<int>("IdCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCard"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Expiration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("int");

                    b.HasKey("IdCard");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.Customer", b =>
                {
                    b.Property<int>("IdCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCustomer"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("int");

                    b.HasKey("IdCustomer");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.Installments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint");

                    b.Property<string>("Installment")
                        .HasColumnType("longtext");

                    b.Property<decimal>("InstallmentValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MonthYear")
                        .HasColumnType("longtext");

                    b.Property<int>("SpendIdSpend")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpendIdSpend");

                    b.ToTable("Installments");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.HasIndex("UserIdUser");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.Spend", b =>
                {
                    b.Property<int>("IdSpend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSpend"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CardIdCard")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerIdCustomer")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Deleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Expenses")
                        .HasColumnType("longtext");

                    b.Property<int>("InstallmentPlan")
                        .HasColumnType("int");

                    b.Property<decimal>("InstallmentValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("int")
                        .HasColumnName("UserIdUser");

                    b.HasKey("IdSpend");

                    b.HasIndex("CardIdCard");

                    b.HasIndex("CustomerIdCustomer");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Spends");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.Card", b =>
                {
                    b.HasOne("SamaCardAll.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.Customer", b =>
                {
                    b.HasOne("SamaCardAll.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.Installments", b =>
                {
                    b.HasOne("SamaCardAll.Core.Models.Spend", "Spend")
                        .WithMany()
                        .HasForeignKey("SpendIdSpend")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spend");
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("SamaCardAll.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SamaCardAll.Core.Models.Spend", b =>
                {
                    b.HasOne("SamaCardAll.Core.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardIdCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SamaCardAll.Core.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerIdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SamaCardAll.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Customer");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
